[package]
name = "jotter"
version = "0.4.0"
entrypoint = "jotter.typ"
authors = ["Andreas Kröpelin"]
license = "MIT"
description = "Handwritten notebook style template for Polylux"
repository = "https://github.com/vvsagar/jotter"
keywords = ["handwritten", "polylux", "presentation", "slides", "slide", "talk", "lecture"]
categories = ["presentation"]

[template]
path = "template"
entrypoint = "slides.typ"
thumbnail = "thumbnail.png"
